### ISSUE TITLE
Services à finir

### ISSUE THREAD

**Issue by MaxleDrut** [MaxleDrut/TP-DASI#13]
- [x] Recup consultation Client
- [x] Recup consultation Employe
- [x] Recup n dernière consult
- [x] tests mediums aux favoris
- [x] Tester récup consultation assignée
- [x] Démarrer consultation
- [x] Terminer consultation
- [x] Récupérer UN Medium
- [x] Top5Medium()
- [x] nbConsultationMedium()
- [x] nbConsultationEmploye()
- [x] Service 3 employés les + populaires pour chaque client, avec nombre de cons.

**Comment by 0nyr** [comment]
Je me charge de nbConsultationMedium() et Top5Medium()

**Comment by rgalle** [comment]
- [ ]  empêcher la demande de plusieurs consultations à la fois par un client

**Comment by 0nyr** [comment]
J'ai ajouté le service recupererTop5Mediums(). Attention : je ne retourne que au maximum 5 médiums, mais ça peut être moins, parce que je ne retourne pas des pairs avec des médiums à 0 consultations.
